### ISSUE TITLE
Does not install on Mac M1

### ISSUE THREAD

**Issue by JoelGodin** [strike-digital/asset_bridge#1]
It says it installed, but it is no where to be found.  Blender 3.2.2 stable
<img width="1614" alt="1" src="https://user-images.githubusercontent.com/9205295/185715440-cb3041f9-f6fe-4812-8549-c5008ddff9c9.png">

**Comment by strike-digital** [comment]
Hi Joel, Just to make sure, you downloaded the release from the [releases page](https://github.com/strike-digital/asset_bridge/releases/tag/0.0.1), and not the zip of the entire repository?

**Comment by JoelGodin** [comment]
No I didn't.  But the releases page does the same:
<img width="1730" alt="2" src="https://user-images.githubusercontent.com/9205295/185718795-0da844e5-e364-40f8-8e89-940fe1a3bff3.png">

**Comment by strike-digital** [comment]
Hmm, yeah, it looks like you downloaded the file marked "source code" from the releases, which isn't the one you want, you want this one:
![image](https://user-images.githubusercontent.com/59890307/185768637-054fdc87-a3f1-458c-9a3e-124615fcab82.png)

**Comment by JoelGodin** [comment]
I don't see V0.0.2, I see this, but yes, first I downloaded source, then I downloaded V0.0.1 but I don't see V0.0.2
<img width="530" alt="1" src="https://user-images.githubusercontent.com/9205295/185769390-c1ebe874-fb38-4194-aeea-d56a184af53c.png">

**Comment by JoelGodin** [comment]
Okay, I found V0.0.3 and that one works.

Closing.

Thanks
