### ISSUE TITLE
I've duplicate assets!

### ISSUE THREAD

**Issue by FidoAnh** [strike-digital/asset_bridge#10]
After install and download, all the assets in Poly Haven  and Ambient CG is twice! I've try to delete all addon and assets and install again but still duplicated!
<img width="250" alt="Capture" src="https://user-images.githubusercontent.com/103020170/231620609-ebc0ea82-e23e-4ddc-9b9f-9db46310ac35.PNG">

**Comment by strike-digital** [comment]
Hi, sorry for the wait, I've been a bit busy recently, but that should be a bit better now.

That's definitely very odd, could you try reinstalling the addon, and see if there is anything printed to the terminal when you are setting up the asset library for the first time?
Thanks!
