### ISSUE TITLE
ASSET BRIDGE and INTERENT CONNECTION

### ISSUE THREAD

**Issue by Roy-Sullivan** [strike-digital/asset_bridge#11]
After following your Youtube instructions for installing the add-on I click on the "Check for new assets and set up asset library" and then U get this ERROR message........

Report: Error
Can't check for new assets, no internet connection detected.

But yet.... I'm connected this second as I write this message. Hmmm 🤔

I really would like to have this working but if all else fails I'm afraid I'll have to request a refund.

**Comment by Roy-Sullivan** [comment]
![Screenshot 2023-04-18 at 7 49 48 AM](https://user-images.githubusercontent.com/131079098/232635022-47fe79a8-793d-442d-9c03-84d28871c3ca.png)

This might help with the issue of NO INTERNET CONNECTION.

**Comment by strike-digital** [comment]
Hi Roy, sorry that's happening, that's pretty weird, I'll have a look at the code and see if I can figure out what's causing it, and then I'll get back when I have something :)

**Comment by Roy-Sullivan** [comment]
Ok… thanks. I appreciate it. For your own information…. I thought your video was actually very funny. It really made me laugh. That was one of the reasons I checked out the Add-on and purchased it, because of your cool video demonstration. 👍

I will wait for your update on what’s happening Sir.



Mr. Roy B. Sullivan
IX Dan Grand Master
ICTF
www.kidokwan.ca

**Comment by Roy-Sullivan** [comment]
Just tried the beta download version and this Screenshot is what I got. It wouldn’t even let me activate it. Whenever I try to activate this screen message pops up.







Mr. Roy B. Sullivan
IX Dan Grand Master
ICTF
www.kidokwan.ca

**Comment by strike-digital** [comment]
Hmm, I think something's gone wrong, I can't see the screenshot?
You may need to upload it directly on GitHub

**Comment by Roy-Sullivan** [comment]
Hope this works and you can see the screenshot. I am a little confused with Github. I usually use Blender Market for all things.

![Screenshot 2023-04-18 at 8 00 50 PM](https://user-images.githubusercontent.com/131079098/232774105-6a70c3cd-2112-42eb-81a7-de72452e7543.png)

**Comment by Roy-Sullivan** [comment]
Just uploaded to GitHub… hopefully.



Mr. Roy B. Sullivan
IX Dan Grand Master
ICTF
www.kidokwan.ca

**Comment by strike-digital** [comment]
Ok, now that's incredibly weird, that shouldn't happen ever, and I'm pretty sure it doesn't have anything to do with the internet bug...

Did you disable and remove the old version of the addon before installing this new one?

**Comment by Roy-Sullivan** [comment]
Yes… I removed the old version and even moved the zip file out of the folder just in case.

Then I installed the beta version and after I received that error message I uninstalled it and tried it again. Got the same message each time.

Ok…. I just tried this routine…………

I installed the beta version….. shut down Blender….. restarted Blender……… installed the beta version again…… and this time it seems to work.


Mr. Roy B. Sullivan
IX Dan Grand Master
ICTF
www.kidokwan.ca

**Comment by Roy-Sullivan** [comment]
here is the actual screenshot after the installation 

![Screenshot 2023-04-18 at 8 26 58 PM](https://user-images.githubusercontent.com/131079098/232777054-0eae1175-02ef-44ad-a767-fc934a7702dc.png)

**Comment by Roy-Sullivan** [comment]
Just uploaded anew screenshot of the working beta version if it helps you again.

Mr. Roy B. Sullivan
IX Dan Grand Master
ICTF
www.kidokwan.ca

**Comment by strike-digital** [comment]
Ok, great! So it all installs correctly now? Can you download assets with it?

**Comment by Roy-Sullivan** [comment]
Yes…. I have tried several downloads. Objects, textures, HDRI’s.

Everything seems to work fine now. Not sure what you did but it is working. Thank you and I’m sorry if I caused any stress.


Mr. Roy B. Sullivan
IX Dan Grand Master
ICTF
www.kidokwan.ca

**Comment by strike-digital** [comment]
Ok, perfect! And don't worry about it, this is basically my job 😅

Although all I did there was confirm that the function to check for an internet connection wasn't working on your machine, so at the moment you could get some weird errors if you try to do stuff, and you actually _don't_ have an internet connection.

So I'll have a look and see if I can find a better way of doing it and then hopefully if you try it, it will work properly 🤞

**Comment by Roy-Sullivan** [comment]
Thanks. I’ll wait for any future updated versions but now it is working ok 🤞


Mr. Roy B. Sullivan
IX Dan Grand Master
ICTF
www.kidokwan.ca

**Comment by strike-digital** [comment]
Ok, I've switched the addon to using a different method for checking for an internet connection, if you get the time could you try this version and see if it still works?
https://we.tl/t-R2oZjGeEaG
Thanks!

**Comment by Roy-Sullivan** [comment]
Yes…. I uninstalled the last version you sent……. Closed Blender…….. restarted Blender……. Installed the 2.0.8 beta version and it still works fine.

Loaded several HDRI’s… Objects…. textures.




Mr. Roy B. Sullivan
IX Dan Grand Master
ICTF
www.kidokwan.ca
