### ISSUE TITLE
i cant install

### ISSUE THREAD

**Issue by ducklee18** [strike-digital/asset_bridge#2]
i addon this zip but nothing change, i try so much time but its still not working :*( help me

**Comment by strike-digital** [comment]
Ok, can you look in the blender console and see if any errors are printed?

**Comment by Maki9009** [comment]
its not installing no errors even pop up it just doesn't install.

**Comment by ducklee18** [comment]
![image](https://user-images.githubusercontent.com/112321273/187084750-b83fe853-f645-4fd8-92ce-cae13a7d485e.png)


> Ok, can you look in the blender console and see if any errors are printed?

**Comment by strike-digital** [comment]
Oh, right, I know what the problem is, you just downloaded the whole repository as a zip file, you should instead download the latest release from the releases page:
https://github.com/strike-digital/asset_bridge/releases/latest
Hope that helps!

**Comment by ducklee18** [comment]
> Oh, right, I know what the problem is, you just downloaded the whole repository as a zip file, you should instead download the latest release from the releases page: https://github.com/strike-digital/asset_bridge/releases/latest Hope that helps!

its working, tysm <3

**Comment by strike-digital** [comment]
Great!
