### ISSUE TITLE
Add "Cancel Download" button

### ISSUE THREAD

**Issue by anon437** [strike-digital/asset_bridge#3]
Adding a button to cancel the download would be useful when download is unexpectedly large or is stalled.  Currently, the only way I know to cancel a download is to close blender through the terminal (Because it will no longer respond).

**Comment by strike-digital** [comment]
Yep, adding a cancel button is planned for the future.
> Because it will no longer respond

That's weird, the UI should always be interactive when using the addon, there shouldn't really be any time when it freezes up...
When does that happen for you?

**Comment by anon437** [comment]
I investigated further.  My wording was incorrect.  The UI is still responsive... until I try to close blender and confirm the close (eg Don't Save Changes).
Then blender freezes (probably because it the main process is no longer updating it), but the window does not disappear until the downloads have been completed, at which point it closes as expected.
Apparently, Blender is waiting for the addon to finish what it is doing.

**Comment by strike-digital** [comment]
Huh, I'd never thought about that, but yeah, I guess that could happen. Generally in my (admittedly fairly limited) testing, closing the window caused the download process to throw an error which caused it to quit and allow the main process to exit as well, but I guess it could also drag on for a while if it was downloading a very big file.

The only thing is, apart from adding a cancel button, I don't really know how to fix this, as there isn't really a way of knowing when blender has been quit. Even then, adding a cancel button may not help much, as it would be quite difficult to interrupt the download before it had finished, and it would be probably more simple to instead just free up the UI and prevent importing and let the download threads finish on their own. That has the downside of continuing to block blender quitting, though, so I'm not sure what the best solution is...

Either way, I'm sure I'll figure something out, I'll do some testing on it soon :)
