### ISSUE TITLE
Show download size

### ISSUE THREAD

**Issue by anon437** [strike-digital/asset_bridge#4]
It would be useful to see the download size before downloading.
Perhaps aligned right in the resolution dropdown box.

**Comment by strike-digital** [comment]
Yeah, I've added this to the current version that I'm working on, but it's still not finished, so it may be a while before it's released.
I've also just started at Uni, so I don't have quite as much time to work on this now :(

![image](https://user-images.githubusercontent.com/59890307/190452967-6567e0c2-d3fc-4bcc-bb67-a0bedaae475b.png)

**Comment by anon437** [comment]
Excellent!
I really appreciate this addon.

**Comment by strike-digital** [comment]
Thank you, hopefully I'll be able to release the update soon :)
