### ISSUE TITLE
World Surface Sampling Settings

### ISSUE THREAD

**Issue by hokutonanto** [strike-digital/asset_bridge#5]
Hello,

I noticed that Asset Bridge sets the World Surface Sampling Settings to Auto, even if in my scene it's originally set to Manual:

Would it be possible to leave the setting unchanged? 
I tend to keep it on manual for a faster viewport response

<img width="294" alt="image" src="https://user-images.githubusercontent.com/23059969/220211791-56a72512-3e7b-498c-b787-5c827d6f559f.png">

Thanks,
Piero

**Comment by strike-digital** [comment]
Hi Piero, thanks for pointing that out, and sorry for the wait! This should be fixed in the [newest prerelease](https://github.com/strike-digital/asset_bridge/releases/tag/2.0.1) :)
