### ISSUE TITLE
2.0.1 Beta release not working

### ISSUE THREAD

**Issue by hokutonanto** [strike-digital/asset_bridge#6]
First off, 

Thanks for taking into account my request about the world settings!

I'm trying the latest beta, but for some reason it's not working on my end.
When I add the path in the preferences, I get this error in the console:

```
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.4\3.4\scripts\startup\bl_ui\space_userpref.py", line 2065, in draw
    draw(context)
  File "C:\Users\Piero\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\asset_bridge\preferences.py", line 187, in draw
    if not task.progress:
AttributeError: 'NoneType' object has no attribute 'progress'

```

**Comment by strike-digital** [comment]
Ah, thanks for pointing that out, I fixed that just after I made the release and I guess I forgot to include it. It should work now in 2.0.2

**Comment by hokutonanto** [comment]
Thank you so much for the quick fix!

**Comment by strike-digital** [comment]
No problem :) Is it all working properly now?

**Comment by strike-digital** [comment]
Perfect!
