### ISSUE TITLE
Blender 3.5 compatibility issue

### ISSUE THREAD

**Issue by hokutonanto** [strike-digital/asset_bridge#7]
Hi there,

It seems Asset Bridge is not working with Blender 3.5
When I add an HDRI map, nothing happens, and the world properties are blank:
<img width="280" alt="image" src="https://user-images.githubusercontent.com/23059969/228623747-8b075ce5-12f8-449a-b0d6-2986eeee536c.png">

Same goes for the models. After I add a model, only an empty is created:
<img width="396" alt="image" src="https://user-images.githubusercontent.com/23059969/228624190-7a94a26c-e278-4691-8790-d0e013eb2e24.png">

**Comment by strike-digital** [comment]
Ah, thanks for pointing that out, I've uploaded a new release which should fix it :)

**Comment by hokutonanto** [comment]
Thanks, @strike-digital !
It's working great now. 

I have another question, but before I ask, is there a way to send a symbolic contribution just to add something in return for your work?

**Comment by strike-digital** [comment]
Great! And don't worry about donating, just giving feedback is more than enough. I really appreciate the thought though :)

I am actually planning to release the addon on Blender Market as well. It'll be completely identical to this one, It'll just help me to continue developing, and also to give something back to the asset creators as well.
This version will always be free, though, and it will get all the same updates as the BM version :)

**Comment by strike-digital** [comment]
Ooh, that's interesting, I hadn't considered that having a different colour space would mess with that part of the code.

Is it 'Generic Data' that it's supposed to be?

Also, do you know what the equivalent for ACES would be (or if there are any other spaces that I might need to support)?

**Comment by hokutonanto** [comment]
Yes, it's generic data for all the other maps that are not albedo.

It seems that Eary, the author of the AGx version that's being proposed, commented here saying that it should already work:
https://projects.blender.org/blender/blender/pulls/106355#issuecomment-911929

I did try both Troy's version and Eary's with the same issue in Asset Bridge.

**Comment by strike-digital** [comment]
Thanks for that link, that taught me something new about the API today :D.

It should be fixed now in the latest release!

**Comment by hokutonanto** [comment]
Awesome! Thanks, @strike-digital !!
I did a few tests, it's working great.

I also see that you have a scale node to adjust the scaling of the textures. I always add a value node, so that really fits my workflow. :)

This is now working better than PolyHaven's!

**Comment by strike-digital** [comment]
Great, I'm really glad it's working well for you! One of the areas I want to focus on is making the imported assets as easy to control as possible, so hopefully there will be more features like that to come :)
