### ISSUE TITLE
Asset Label stuck on viewport

### ISSUE THREAD

**Issue by hokutonanto** [strike-digital/asset_bridge#8]
Hi @strike-digital 

I'm here again with a new issue.
Sometimes it happens that the download is not completed correctly.
In that case, the placeholder label that appears on the viewport, gets stuck, and when I click on the little X icon on it, I get an error:

```
Error importing asset ph_belfast_farmhouse:
Traceback (most recent call last):
  File "C:\Users\Piero\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\asset_bridge\helpers\assets.py", line 171, in import_asset
    imported = asset.import_asset(context)
  File "C:\Users\Piero\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\asset_bridge\apis\polyhaven\ph_asset.py", line 114, in import_asset
    image_file = files[0]
IndexError: list index out of range
```

Here's a screen capture:
https://user-images.githubusercontent.com/23059969/229967020-b56715fa-46e4-40ff-949e-d167c05e87ea.mp4

**Comment by strike-digital** [comment]
Thanks for reporting that, I hadn't realized that that was broken, it seems I just forgot to update it when I changed the internal system for cancelling downloads.

Also, currently it seems that ambientCG.com is down, so I added some error handling for that that should make it simpler for the user to deal with.

**Comment by hokutonanto** [comment]
Thanks, @strike-digital 
I installed the latest 2.0.5
The error is gone, but so is also the World object creation which becomes empty after I add an HDRI :)
<img width="304" alt="image" src="https://user-images.githubusercontent.com/23059969/230240041-6bd23cd0-8aad-408d-a5ea-7861f099b4b3.png">

**Comment by strike-digital** [comment]
Hmm, weird, I can't replicate it, can you see if there are any errors printed in the terminal?

**Comment by hokutonanto** [comment]
Never mind, just checked the console, that's Blender's odd way of handling the preferences.
The library path was intact, with the path pointing to the right folder. But apparently, Blender needs to get the path reassigned for some reason.

It's working fine now 👍

**Comment by strike-digital** [comment]
Great, thanks for reporting it anyway, I think you've single-handedly found more bugs than me 😅
