### ISSUE TITLE
cache/previews Missing & AttributeError: 'Dirs' object has no attribute 'dummy_assets' - Error (see console)

### ISSUE THREAD

**Issue by KeyRie** [strike-digital/asset_bridge#9]
Hii, first of all thank you so much for creating this amazing addon! Would like you to know if i found a bug that you can fix.

In the v2.0.6 (latest version) (blender still detect it as 2.0.5, i think you need to change the version in _init.py) there's a bug where the console says '//cache/previews is missing' and i couldn't 'Download asset previews'. I fix it by simply adding the new folder 'cache' and 'previews' inside of it from the dir of the addon (appdata/roaming/blender foundation/{blender version}/scripts/addons/asset_bridge/). I think you remove it somehow in this version? May be on the next one those folder should be added already. (I have no idea if the github version and the blendermarket is the same one).

Once those folder were made and i've download , the console says:

line 220, in draw
    dummy_blends = [f for f in DIRS.dummy_assets.iterdir() if f.suffix == ".blend"]
AttributeError: 'Dirs' object has no attribute 'dummy_assets'

Hope this could be fixed in the next version!

I use blender 3.5

**Comment by strike-digital** [comment]
Ah, thanks for reporting that, I think there was an issue when I uploaded the release, for some reason it didn't have the correct version.

I've uploaded the proper one now, so it should work :)

And just to clear it up, yes, both this version and the blender market version are identical, but luckily I uploaded the correct version there 😅

Hope that helps!
